name: Auto Merge on "merge me" Comment

on:
  issue_comment:
    types: [created]

jobs:
  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request && 
      github.event.comment.body == 'merge me'
    steps:

      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1184072
          private-key: ${{ secrets.MERGEMATE_KEY }}

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@d97294d304604fa98a2600a6e2f916a84b596dc7 # v2.0.0
        id: comment-branch

      - name: Set PR_HEAD_REF
        run: |
          echo "PR_HEAD_REF=${{ steps.comment-branch.outputs.head_ref }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "ORG_NAME=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
          echo "LAST_COMMIT=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Check PR Approval by Bot
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Checking approvals for PR: $PR_HEAD_REF..."
          if gh pr view $PR_HEAD_REF --repo $ORG_NAME/$REPO --json reviews --jq '[.reviews[] | select(.state == "APPROVED" and .author.login == "mergem8")] | length' | grep -qw "1"; then
            echo "✅ PR is approved by the bot."
            echo "APPROVED_BY_BOT=true" >> $GITHUB_ENV
          else
            echo "❌ PR is NOT approved by the bot. Exiting."
            exit 0
          fi

      - name: Merge the PR
        if: env.APPROVED_BY_BOT == 'true'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Merging PR #${{ env.PR_NUMBER }}..."
          gh pr merge --repo $ORG_NAME/$REPO --admin --squash --delete-branch $PR_HEAD_REF|| echo "⚠️ Auto-merge failed. Check branch protections."
          echo "✅ PR #${{ env.PR_NUMBER }} merged successfully!"