name: Emergency review bypass

on:
  pull_request_target:
    types:
      - labeled

permissions: write-all

jobs:
  approve:
    name: Approve
    runs-on: ubuntu-latest
    if: github.event.label.name == 'emergency'
    steps:
    
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1170727
          private-key: ${{ secrets.APP_PRIVATE_KEY_1170727 }}
          
      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      
      - name: Approve
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          MERGE_LABELS: "emergency"
          LOG: DEBUG
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          
      - name: Merge PR
        run: gh pr merge --admin --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
