name: Emergency review bypass

on:
  pull_request_target:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  approve:
    name: Approve
    runs-on: ubuntu-latest
    if: github.event.label.name == 'emergency'
    steps:

      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with: 
          ref: main

      - name: Emergency Approve
        uses: ./.github/workflows/actions/pr-emergency-approve
        with:
          BYPASS_TEAM: bot
          GHAPP_ID: 1184072
          GHAPP_SSH_KEY: ${{ secrets.MERGEMATE_KEY }}