name: Emergency Merge

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request && 
      github.event.comment.body == 'merge me' &&
      github.event.label.name == 'emergency'
    steps:

      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with: 
          ref: main

      - name: Emergency Approve
        uses: ./.github/workflows/actions/pr-emergency-merge
        with:
          GHAPP_ID: 1184072
          GHAPP_SSH_KEY: ${{ secrets.MERGEMATE_KEY }}