name: Emergency review bypass

on:
  pull_request_target:
    types:
      - labeled

permissions: write-all

jobs:
  approve:
    name: Approve
    runs-on: ubuntu-latest
    if: github.event.label.name == 'emergency'
    steps:
    
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1170727
          private-key: ${{ secrets.APP_PRIVATE_KEY_1170727 }}
          
      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          
      - name: Set up GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug PR API Response
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
      
          echo "Fetching PR details..."
          gh api repos/$REPO/pulls/$PR_NUMBER | tee pr_response.json

          REVIEWERS=$(gh api repos/$REPO/pulls/$PR_NUMBER --jq '.requested_reviewers | map(.login) | join(", ")')
          echo "Reviewers: ${REVIEWERS:-None}"
    
      - name: Get PR Reviewers using GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}

          echo "Fetching PR reviewers..."
          REVIEWERS=$(gh api repos/$REPO/pulls/$PR_NUMBER --jq '.requested_reviewers[].login')

          echo "Reviewers for PR #$PR_NUMBER:"
          echo "$REVIEWERS"

      - name: (Optional) Fetch Team Members using GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: "your-org"
          TEAM_SLUG: "your-team"
        run: |
          echo "Fetching team members..."
          TEAM_MEMBERS=$(gh api orgs/$ORG_NAME/teams/$TEAM_SLUG/members --jq '.[].login')

          echo "Team Members:"
          echo "$TEAM_MEMBERS"

      - name: Check if PR Author is in CODEOWNERS
        id: check-codeowner
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          CODEOWNERS="${{ steps.codeowners.outputs.owners }}"
          if echo "$CODEOWNERS" | grep -wq "$PR_AUTHOR"; then
            echo "✅ $PR_AUTHOR is a CODEOWNER. Proceeding with auto-merge."
            echo "IS_CODEOWNER=true" >> $GITHUB_ENV
          else
            echo "⛔ ERROR: $PR_AUTHOR is NOT a CODEOWNER! Merge is blocked."
            exit 1
          fi
          
      - name: Approve
        if: env.IS_CODEOWNER == 'true'
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          
      - name: Merge PR
        run: gh pr merge --admin --squash "$PR_URL"
        if: env.IS_CODEOWNER == 'true'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
