name: Emergency review bypass

on:
  pull_request_target:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REPO: ${{ github.repository }}
  ORG_NAME: ${{ github.repository_owner }}
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}

jobs:
  approve:
    name: Approve
    runs-on: ubuntu-latest
    if: github.event.label.name == 'emergency'
    steps:

      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/workflows/actions/pr-emergency-approve
        with:
          bypass_team: bot
          GHAPP_ID: 1184072
          GHAPP_SSH_KEY: ${{ secrets.MERGEMATE_KEY }}
      
      # - name: Merge PR
      #   if: env.AUTHOR_IS_MEMBER == 'true'
      #   run: |
      #     echo "🚀 Attempting to auto-merge PR #$PR_NUMBER..."
      #     gh pr merge --admin --squash "$PR_URL" || echo "⚠️ Auto-merge failed. Check branch protections."
      #   env:
      #     PR_URL: ${{ github.event.pull_request.html_url }}
      #     GH_TOKEN: ${{ steps.app-token.outputs.token }}
