name: PR Informational Message

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    name: Provide PR Informational messages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc-sla
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Pull Request Review Process

      - name: Create comment with agreements 
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 #v4.0.0
        with:
          comment-id: ${{ steps.fc-sla.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: .github/templates/template-rules.md
          edit-mode: replace

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc-tg
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: GitHub Actions Pull Request commands

      - name: Create comment with cf-tg commands
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 #v4.0.0
        with:
          comment-id: ${{ steps.fc-tg.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: .github/templates/template-comment-flow.md
          edit-mode: replace