name: "PR Analytics"
on:
  workflow_dispatch:
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@1c87bb2a69668014452df3f54fb1ff55874eddab
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If you're interested in analytics for a single repository without team breakdowns, GITHUB_TOKEN is sufficient.
          GITHUB_OWNER_FOR_ISSUE: "RodeTech" # Make sure to specify the owner of the repository where the issue will be created
          GITHUB_REPO_FOR_ISSUE: "demo-repository" # Make sure to specify the name of the repository where the issue will be created
          GITHUB_OWNERS_REPOS: "RodeTech/demo-repository" # Be sure to list the owner and repository name in the format owner/repo
          LABELS: "Report"
          TIMEZONE: "Europe/Athens"
          REPORT_PERIOD: "months:1"
          AGGREGATE_VALUE_METHODS: average
          PERIOD_SPLIT_UNIT: months
          TOP_LIST_AMOUNT: 5
          ALLOW_ANALYTICS: false
