name: PR Review Stats
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
permissions: write-all
  
jobs:
  review-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get review stats
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "all",
            });

            let reviewers = {};
            for (const pr of pulls) {
              const { data: reviews } = await github.rest.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              });

              for (const review of reviews) {
                const user = review.user.login;
                reviewers[user] = (reviewers[user] || 0) + 1;
              }
            }

            console.log("Reviewer stats:", reviewers);

      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@main
        with:
          publishAs: DESCRIPTION
          telemetry: false
